"""empty message

Revision ID: 1cd6aded3147
Revises: 7e7b03f2e87f
Create Date: 2021-05-27 17:31:21.871687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd6aded3147'
down_revision = '7e7b03f2e87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_messages', 'is_visible')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
