"""empty message

Revision ID: 6a6904d87522
Revises: dd5ca01f71ac
Create Date: 2021-05-27 16:24:04.501069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6904d87522'
down_revision = 'dd5ca01f71ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('direct_messages', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('direct_messages', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
