"""empty message

Revision ID: dd5ca01f71ac
Revises: 7e7b03f2e87f
Create Date: 2021-05-27 15:29:56.013323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5ca01f71ac'
down_revision = '7e7b03f2e87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_messages', 'is_visible')
    # ### end Alembic commands ###
