"""empty message

Revision ID: 7e7b03f2e87f
Revises: dd7840fddbdf
Create Date: 2021-05-24 13:15:22.405667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7b03f2e87f'
down_revision = 'dd7840fddbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_messages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('direct_messages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_messages', 'created_at')
    op.drop_column('channel_messages', 'created_at')
    # ### end Alembic commands ###
