"""empty message

Revision ID: 4a853e082397
Revises: 6a6904d87522
Create Date: 2021-05-27 17:08:33.110659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a853e082397'
down_revision = '6a6904d87522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_messages', 'is_visible')
    op.add_column('users', sa.Column('is_visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_visible')
    op.add_column('direct_messages', sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
